# syntax=docker/dockerfile:1

# Latest as of 2024-09-30.
ARG GO_VERSION="1.23.1-alpine@sha256:ac67716dd016429be8d4c2c53a248d7bcdf06d34127d3dc451bda6aa5a87bc06"

FROM golang:${GO_VERSION}

# Latest versions as of 2024-09-30.
# TODO: Include and enforce checksum. Trusting the Golang proxy for now.
ARG CFSSL_VERSION="1.6.5"

# Install cfssl and cfssljson.
RUN go install github.com/cloudflare/cfssl/cmd/...@v${CFSSL_VERSION}

CMD ["/go/bin/cfssl"]
