---
name: Tests

'on':
  pull_request:

jobs:
  # Make sure the binaries are built without error.
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # NOTE: We trust Github.
      - uses: actions/checkout@v4
      - name: Build
        run: |
          # No need to build the protobuf image in the CI.
          mkdir -p .build && touch .build/docker-protobuf
          make build -j

  # Run the actual tests.
  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      # NOTE: We trust GitHub.
      - uses: actions/checkout@v4
      - name: Run go test
        run: |
          # No need to build the protobuf image in the CI.
          mkdir -p .build && touch .build/docker-protobuf
          make test -j
